web:
  build: .
  ports:
    - "49155:80"
  volumes:
    - ./worldapi:/opt/www/worldapi
  links:
    - db
db:
  image: mysql/mysql-server:5.6
  volumes:
   - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=rootpwd
    - MYSQL_DATABASE=apidb
    - MYSQL_USER=apiusr
    - MYSQL_PASSWORD=apipass
